/******************************************************************************
* MUI_ACT - MUI-ARexx/Commodity-Test
* (C)2022 M.Volkel (mario.volkel@outlook.com)
*******************************************************************************/

// Comment templates

/******************************************************************************
*
*******************************************************************************/

/*-----------------------------------------------------------------------------
-
------------------------------------------------------------------------------*/

/******************************************************************************
* Header-Files
*******************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <exec/memory.h>
#include <libraries/gadtools.h>
#include <libraries/mui.h>

#include <pragma/diskfont_lib.h>
#include <proto/exec.h>
#include <pragma/graphics_lib.h>
#include <pragma/muimaster_lib.h>

/******************************************************************************
* Prototypes
*******************************************************************************/
void init(void);
void end(void);
struct ObjApp *CreateApp(void);
void DisposeApp(struct ObjApp *ObjectApp);

/******************************************************************************
* Definitions
*******************************************************************************/
#define MAKE_ID(a, b, c, d) ((ULONG)(a) << 24 | (ULONG)(b) << 16 | (ULONG)(c) << 8 | (ULONG)(d))

/******************************************************************************
* Global Variables
*******************************************************************************/
struct IntuitionBase *IntuitionBase;
struct Library *MUIMasterBase;

schar buffer[40];

struct ObjApp *ObjectApp;

char errorMsg[100];
struct ObjApp *App = NULL; /* Object */

/******************************************************************************
* Main-Program
*******************************************************************************/

/*-----------------------------------------------------------------------------
- main()
------------------------------------------------------------------------------*/
int main(int argc, char *argv[])
{
	BOOL running = TRUE;
	ULONG signal;

	/* Program initialisation : generated by GenCodeC */
	init();

	/* Create Object : generated by GenCodeC */
	if (!(App = CreateApp()))
	{
		printf("Can't Create App\n");
		end();
	}

	if (preset = AllocVec(sizeof(struct LCDPreset), MEMF_CLEAR))
	{
		while (running)
		{
			switch (DoMethod(App->App, MUIM_Application_Input, &signal))
			{
				default:
					break;
			}

			if (running && signal)
				Wait(signal);
		}
		FreeVec(preset);
	}
	else
		sprintf(errorMsg, "Not enough Memory for Preset");

	DisposeApp(App);
	end();
}

/*-----------------------------------------------------------------------------
- init()
------------------------------------------------------------------------------*/
void init(void)
{
	if (!(IntuitionBase = (struct IntuitionBase *)OpenLibrary("intuition.library", 37)))
	{
		printf("Can't Open Intuition Library\n");
		exit(20);
	}
	if (!(MUIMasterBase = OpenLibrary(MUIMASTER_NAME, MUIMASTER_VMIN)))
	{
		printf("Can't Open MUIMaster Library\n");
		CloseLibrary((struct Library *)IntuitionBase);
		exit(20);
	}

	if (!(Font2 = OpenDiskFont(&HD447807)))
		end();
}

/*-----------------------------------------------------------------------------
- end()
------------------------------------------------------------------------------*/
void end(void)
{
	if (Font2)
		CloseFont(Font2);

	CloseLibrary(MUIMasterBase);
	CloseLibrary((struct Library *)IntuitionBase);
	exit(20);
}

/*-----------------------------------------------------------------------------
- CreateApp()
------------------------------------------------------------------------------*/
struct ObjApp *CreateApp(void)
{
	struct ObjApp *ObjectApp;

	//APTR	MNlabel0Project, MNlabel0New, MNlabel0BarLabel0, MNlabel0Load, MNlabel0Save;
	//APTR	MNlabel0SaveAa, MNlabel0Transfer, MNlabel0BarLabel1, MNlabel0About;
	//APTR	MNlabel0BarLabel2, MNlabel0Hide, MNlabel0Quit, MNlabel0Item, MNlabel0Init;
	//APTR	MNlabel0Copy, MNlabel0Paste, MNlabel0BarLabel3, MNlabel0ClearScreen;
	//APTR	MNlabel0On, MNlabel0Off
	APTR	GROUP_ROOT_0, GR_grp_2, LA_label_0, LA_label_1;
	APTR	GR_grp_3, GR_grp_7, GR_grp_8, GR_grp_4, LA_label_2, LA_label_3, LA_label_4;
	APTR	LA_label_5, LA_label_8, GR_grp_5, LA_label_9, GR_grp_6, LA_label_10;
	APTR	GR_grp_0;

	//char *listviewItems[] = {"Amiga 500", "Amiga 1200", "C64", NULL}; 

	if (!(ObjectApp = AllocVec(sizeof(struct ObjApp), MEMF_CLEAR)))
		return (NULL);

	if (!(mcc = MUI_CreateCustomClass(NULL, MUIC_Area, NULL, sizeof(struct MyData), MyDispatcher)))
	{
		printf("Could not create custom class.\n");
		end();
	}

	ObjectApp->STR_TX_label_1 = NULL;

	ObjectApp->CY_label_0Content[0] = "off";
	ObjectApp->CY_label_0Content[1] = "on";
	ObjectApp->CY_label_0Content[2] = NULL;
	ObjectApp->CY_label_1Content[0] = "100ms";
	ObjectApp->CY_label_1Content[1] = "500ms";
	ObjectApp->CY_label_1Content[2] = "1s";
	ObjectApp->CY_label_1Content[3] = "5s";
	ObjectApp->CY_label_1Content[4] = "10s";
	ObjectApp->CY_label_1Content[5] = "1min";
	ObjectApp->CY_label_1Content[6] = NULL;
	ObjectApp->CY_label_2Content[0] = "Fill";
	ObjectApp->CY_label_2Content[1] = "Text";
	ObjectApp->CY_label_2Content[2] = "Bargraph";
	ObjectApp->CY_label_2Content[3] = NULL;
	ObjectApp->CY_label_3Content[0] = "1 Line";
	ObjectApp->CY_label_3Content[1] = "2 Lines";
	ObjectApp->CY_label_3Content[2] = "3 Lines";
	ObjectApp->CY_label_3Content[3] = "4 Lines";
	ObjectApp->CY_label_3Content[4] = NULL;

	LA_label_0 = Label("Backlight");

	ObjectApp->CY_label_0 = CycleObject,
	MUIA_HelpNode, "CY_label_0",
	MUIA_Frame, MUIV_Frame_Button,
	MUIA_Cycle_Entries, ObjectApp->CY_label_0Content,
	End;

	LA_label_1 = Label("Refresh");

	ObjectApp->CY_label_1 = CycleObject,
	MUIA_HelpNode, "CY_label_1",
	MUIA_Frame, MUIV_Frame_Button,
	MUIA_Cycle_Entries, ObjectApp->CY_label_1Content,
	End;

	GR_grp_2 = GroupObject,
	MUIA_HelpNode, "GR_grp_2",
	MUIA_Frame, MUIV_Frame_Group,
	MUIA_FrameTitle, "Global",
	MUIA_Group_Columns, 2,
	MUIA_Group_VertSpacing, 4,
	Child, LA_label_0,
	Child, ObjectApp->CY_label_0,
	Child, LA_label_1,
	Child, ObjectApp->CY_label_1,
	End;

	ObjectApp->LV_label_1 = ListObject,
	MUIA_Frame, MUIV_Frame_InputList,
	End;

	ObjectApp->LV_label_1 = ListviewObject,
		MUIA_HelpNode, "LV_label_1",
		//MUIA_Listview_List, ObjectApp->LV_label_1,
		MUIA_Listview_Input, TRUE,
		MUIA_Listview_List, ListObject,
		InputListFrame,
		MUIA_List_ConstructHook, MUIV_List_ConstructHook_String,
		MUIA_List_DestructHook, MUIV_List_DestructHook_String,
		End,
	End;

	ObjectApp->STR_label_4 = StringObject,
		MUIA_Frame, MUIV_Frame_String,
		MUIA_HelpNode, "STR_label_4",
	End;

	ObjectApp->BT_label_7 = SimpleButton("Add");
	ObjectApp->BT_label_8 = SimpleButton("Del");

	GR_grp_8 = GroupObject,
	MUIA_HelpNode, "GR_grp_8",
	MUIA_Group_Columns, 2,
	Child, ObjectApp->BT_label_7,
	Child, ObjectApp->BT_label_8,
	End;

	GR_grp_7 = GroupObject,
	MUIA_HelpNode, "GR_grp_7",
	MUIA_Group_Rows, 3,
	Child, ObjectApp->LV_label_1,
	Child, ObjectApp->STR_label_4,
	Child, GR_grp_8,
	End;

	LA_label_2 = Label("Type:");

	ObjectApp->CY_label_2 = CycleObject,
	MUIA_HelpNode, "CY_label_2",
	MUIA_Frame, MUIV_Frame_Button,
	MUIA_Cycle_Entries, ObjectApp->CY_label_2Content,
	End;

	LA_label_3 = Label("Value:");

	ObjectApp->CY_label_3 = CycleObject,
	MUIA_HelpNode, "CY_label_3",
	MUIA_Frame, MUIV_Frame_Button,
	MUIA_Cycle_Entries, ObjectApp->CY_label_3Content,
	End;

	LA_label_4 = Label("Label:");

	ObjectApp->STR_label_0 = StringObject,
	MUIA_Frame, MUIV_Frame_String,
	MUIA_HelpNode, "STR_label_0",
	End;

	LA_label_5 = Label("Value:");

	ObjectApp->STR_label_1 = StringObject,
	MUIA_Frame, MUIV_Frame_String,
	MUIA_HelpNode, "STR_label_1",
	End;

	LA_label_8 = Label("X:");

	ObjectApp->STR_label_2 = StringObject,
	MUIA_Frame, MUIV_Frame_String,
	MUIA_HelpNode, "STR_label_2",
	MUIA_String_Accept, "-0123456789",
	MUIA_String_MaxLen, 3,
	End;

	ObjectApp->BT_label_3 = SimpleButton("-");
	ObjectApp->BT_label_4 = SimpleButton("+");

	GR_grp_5 = GroupObject,
	MUIA_HelpNode, "GR_grp_5",
	MUIA_Group_Columns, 3,
	Child, ObjectApp->STR_label_2,
	Child, ObjectApp->BT_label_3,
	Child, ObjectApp->BT_label_4,
	End;

	LA_label_9 = Label("Y:");

	ObjectApp->STR_label_3 = StringObject,
	MUIA_Frame, MUIV_Frame_String,
	MUIA_HelpNode, "STR_label_3",
	MUIA_String_Accept, "-0123456789",
	MUIA_String_MaxLen, 3,
	End;

	ObjectApp->BT_label_5 = SimpleButton("-");
	ObjectApp->BT_label_6 = SimpleButton("+");

	GR_grp_6 = GroupObject,
	MUIA_HelpNode, "GR_grp_6",
	MUIA_Group_Columns, 3,
	Child, ObjectApp->STR_label_3,
	Child, ObjectApp->BT_label_5,
	Child, ObjectApp->BT_label_6,
	End;

	LA_label_10 = Label("Total Items:");

	ObjectApp->TX_label_1 = TextObject,
	MUIA_Background, MUII_TextBack,
	MUIA_Frame, MUIV_Frame_Text,
	MUIA_Text_Contents, ObjectApp->STR_TX_label_1,
	MUIA_Text_SetMin, TRUE,
	End;

	GR_grp_4 = GroupObject,
	MUIA_HelpNode, "GR_grp_4",
	MUIA_Group_Columns, 2,
	Child, LA_label_2,
	Child, ObjectApp->CY_label_2,
	Child, LA_label_3,
	Child, ObjectApp->CY_label_3,
	Child, LA_label_4,
	Child, ObjectApp->STR_label_0,
	Child, LA_label_5,
	Child, ObjectApp->STR_label_1,
	Child, LA_label_8,
	Child, GR_grp_5,
	Child, LA_label_9,
	Child, GR_grp_6,
	Child, LA_label_10,
	Child, ObjectApp->TX_label_1,
	End;

	GR_grp_3 = GroupObject,
	MUIA_HelpNode, "GR_grp_3",
	MUIA_Frame, MUIV_Frame_Group,
	MUIA_FrameTitle, "Items",
	MUIA_Group_Horiz, TRUE,
	Child, GR_grp_7,
	Child, GR_grp_4,
	End;

	ObjectApp->BT_label_0 = TextObject,
	ButtonFrame,
	MUIA_Background, MUII_ButtonBack,
	MUIA_ControlChar, '1',
	MUIA_Text_Contents, "Save",
	MUIA_Text_PreParse, "\033c",
	MUIA_Text_HiChar, '1',
	MUIA_HelpNode, "BT_label_0",
	MUIA_InputMode, MUIV_InputMode_RelVerify,
	End;

	ObjectApp->BT_label_1 = TextObject,
	ButtonFrame,
	MUIA_Background, MUII_ButtonBack,
	MUIA_ControlChar, '2',
	MUIA_Text_Contents, "Test",
	MUIA_Text_PreParse, "\033c",
	MUIA_Text_HiChar, '2',
	MUIA_HelpNode, "BT_label_1",
	MUIA_InputMode, MUIV_InputMode_RelVerify,
	End;

	ObjectApp->BT_label_2 = TextObject,
	ButtonFrame,
	MUIA_Background, MUII_ButtonBack,
	MUIA_ControlChar, '3',
	MUIA_Text_Contents, "Cancel",
	MUIA_Text_PreParse, "\033c",
	MUIA_Text_HiChar, '3',
	MUIA_HelpNode, "BT_label_2",
	MUIA_InputMode, MUIV_InputMode_RelVerify,
	End;

	GR_grp_0 = GroupObject,
	MUIA_HelpNode, "GR_grp_0",
	MUIA_Group_Horiz, TRUE,
	Child, ObjectApp->BT_label_0,
	Child, ObjectApp->BT_label_1,
	Child, ObjectApp->BT_label_2,
	End;

	GROUP_ROOT_0 = GroupObject,
	Child, ObjectApp->MyObj = NewObject(mcc->mcc_Class, NULL, TextFrame, MUIA_Background, MUII_BACKGROUND, TAG_DONE),
	Child, GR_grp_2,
	Child, GR_grp_3,
	Child, GR_grp_0,
	End;

	ObjectApp->WI_label_0 = WindowObject,
	MUIA_Window_Title, "LCD-Com V0.5",
	MUIA_Window_ID, MAKE_ID('0', 'W', 'I', 'N'),
	MUIA_Window_SizeGadget, FALSE,
	WindowContents, GROUP_ROOT_0,
	End;

	ObjectApp->App = ApplicationObject,
	MUIA_Application_Author, "AppAuthor",
	MUIA_Application_Menustrip, ObjectApp->MN_label_0 = MUI_MakeObject(MUIO_MenustripNM, MenuData1, 0),
	MUIA_Application_Base, "AppBase",
	MUIA_Application_Title, "LCD-Com",
	MUIA_Application_Version, "$VER:  LCD-Com V0.5",
	MUIA_Application_Copyright, "(C)2022 M.Volkel",
	MUIA_Application_Description, "Commodity for Serial LC-Display",
	SubWindow, ObjectApp->WI_label_0,
	End;

	if (!ObjectApp->App)
	{
		FreeVec(ObjectApp);
		return (NULL);
	}

	DoMethod(ObjectApp->WI_label_0,
			 MUIM_Window_SetCycleChain, ObjectApp->CY_label_0,
			 ObjectApp->CY_label_1,
			 ObjectApp->LV_label_1,
			 ObjectApp->STR_label_4,
			 ObjectApp->BT_label_7,
			 ObjectApp->BT_label_8,
			 ObjectApp->BT_label_9,
			 ObjectApp->BT_label_10,
			 ObjectApp->CY_label_2,
			 ObjectApp->CY_label_3,
			 ObjectApp->STR_label_0,
			 ObjectApp->STR_label_1,
			 ObjectApp->STR_label_2,
			 ObjectApp->BT_label_3,
			 ObjectApp->BT_label_4,
			 ObjectApp->STR_label_3,
			 ObjectApp->BT_label_5,
			 ObjectApp->BT_label_6,
			 ObjectApp->BT_label_0,
			 ObjectApp->BT_label_1,
			 ObjectApp->BT_label_2,
			 NULL);

	// Window-Close
	DoMethod(ObjectApp->WI_label_0, MUIM_Notify, MUIA_Window_CloseRequest, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, MUIV_Application_ReturnID_Quit);

	// Button-Press: Save, Test, Cancel
	DoMethod(ObjectApp->BT_label_0, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Save);
	DoMethod(ObjectApp->BT_label_1, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Test);
	DoMethod(ObjectApp->BT_label_2, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Cancel);

	// Button-Press: Add, Del, Up, Down
	DoMethod(ObjectApp->BT_label_7, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Add);
	DoMethod(ObjectApp->BT_label_8, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Del);
	DoMethod(ObjectApp->BT_label_9, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Up);
	DoMethod(ObjectApp->BT_label_10, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Down);

	// Listview-Methods
	set(ObjectApp->LV_label_1, MUIA_List_Active, MUIV_List_Active_Top);
	DoMethod(ObjectApp->LV_label_1, MUIM_Notify, MUIA_List_Active, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_LV);
	DoMethod(ObjectApp->LV_label_1, MUIM_Notify, MUIA_Listview_SelectChange, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_LV);

	// Copy Listview-Items
	//for (i = 0; listviewItems[i] != NULL; i++)
	//	DoMethod(ObjectApp->LV_label_1, MUIM_List_InsertSingle, listviewItems[i], MUIV_List_Insert_Bottom);

	// String-Gadget Methods
	set(ObjectApp->STR_label_4, MUIA_String_AttachedList, ObjectApp->LV_label_1);
	DoMethod(ObjectApp->STR_label_4, MUIM_Notify, MUIA_String_Acknowledge, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID,  ID_STR);

	DoMethod(ObjectApp->BT_label_3, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_XM);
	DoMethod(ObjectApp->BT_label_4, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_XP);
	DoMethod(ObjectApp->BT_label_5, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_YM);
	DoMethod(ObjectApp->BT_label_6, MUIM_Notify, MUIA_Pressed, TRUE, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_YP);

	DoMethod(ObjectApp->CY_label_0, MUIM_Notify, MUIA_Cycle_Active, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Backlight);
	DoMethod(ObjectApp->CY_label_1, MUIM_Notify, MUIA_Cycle_Active, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Refresh);
	DoMethod(ObjectApp->CY_label_2, MUIM_Notify, MUIA_Cycle_Active, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Type);
	DoMethod(ObjectApp->CY_label_3, MUIM_Notify, MUIA_Cycle_Active, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID, ID_Value);

	DoMethod(ObjectApp->STR_label_0, MUIM_Notify, MUIA_String_Acknowledge, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID,  ID_Label);
	DoMethod(ObjectApp->STR_label_1, MUIM_Notify, MUIA_String_Acknowledge, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID,  ID_ValueName);

	DoMethod(ObjectApp->STR_label_2, MUIM_Notify, MUIA_String_Acknowledge, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID,  ID_XPos);
	DoMethod(ObjectApp->STR_label_3, MUIM_Notify, MUIA_String_Acknowledge, MUIV_EveryTime, ObjectApp->App, 2, MUIM_Application_ReturnID,  ID_YPos);

	// Open Window
	set(ObjectApp->WI_label_0, MUIA_Window_Open, TRUE);

	/*
					DisplayBeep(0);
					get(App->KN_label_0, MUIA_Numeric_Value, &knobVal);
					sprintf(buffer, "%02d", knobVal);
					set(App->STR_label_4, MUIA_String_Contents, buffer);
					break;
	*/
	return (ObjectApp);
}

/*-----------------------------------------------------------------------------
- DisposeApp()
------------------------------------------------------------------------------*/
void DisposeApp(struct ObjApp *ObjectApp)
{
	MUI_DisposeObject(ObjectApp->App);
	FreeVec(ObjectApp);
}
